# Generated by Django 3.2.5 on 2021-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='usuario'),
        ),
    ]
