# Generated by Django 3.2.4 on 2021-07-12 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artista',
            fields=[
                ('idArtista', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Artista')),
                ('nombreartista', models.CharField(max_length=50, verbose_name='Nombre Artista')),
            ],
        ),
        migrations.CreateModel(
            name='obra',
            fields=[
                ('idObra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Obra')),
                ('detalle', models.CharField(max_length=50, verbose_name='Detalle')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
                ('categorias', models.CharField(max_length=50, verbose_name='Categoria')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artista')),
            ],
        ),
    ]
