# Generated by Django 3.2.4 on 2021-07-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='idArtista',
            new_name='idartista',
        ),
    ]
