# Generated by Django 3.2.4 on 2021-07-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_idartista_artista_idartista'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img', verbose_name='Imagen'),
        ),
    ]
